package org.labun.jooq.generator.generation

object GeneratorsNames {

  val SCHEMA = "DEFAULT:SCHEMA"
  val SCHEMA_KEYS = "DEFAULT:SCHEMA_KEYS"
  val SCHEMA_SEQUENCES = "DEFAULT:SCHEMA_SEQUENCES"
  val TABLE = "DEFAULT:TABLE"
  val TABLE_RECORD = "DEFAULT:TABLE_RECORD"
  val TABLE_COLUMNS = "DEFAULT:TABLE_COLUMNS"
  val REPOSITORY = "DEFAULT:REPOSITORY"
  val CATALOG = "DEFAULT:CATALOG"
  val SCHEMA_INDEXES = "DEFAULT:SCHEMA_INDEXES"
}