package org.labun.jooq.subgenerators.column;

import javax.annotation.Generated;

/**
 * This class is generated by jooq-generator.
 */
@Generated({"jooq-generator:"})
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OwnersColumns {

    /**
     * The column <code>PUBLIC.OWNERS.ID</code>.
     */
    public final String ID = "ID";

    /**
     * The column <code>PUBLIC.OWNERS.FIRST_NAME</code>.
     */
    public final String FIRST_NAME = "FIRST_NAME";

    /**
     * The column <code>PUBLIC.OWNERS.LAST_NAME</code>.
     */
    public final String LAST_NAME = "LAST_NAME";

    /**
     * The column <code>PUBLIC.OWNERS.ADDRESS</code>.
     */
    public final String ADDRESS = "ADDRESS";

    /**
     * The column <code>PUBLIC.OWNERS.CITY</code>.
     */
    public final String CITY = "CITY";

    /**
     * The column <code>PUBLIC.OWNERS.TELEPHONE</code>.
     */
    public final String TELEPHONE = "TELEPHONE";

}