package org.labun.jooq.subgenerators.column;

import javax.annotation.Generated;

/**
 * This class is generated by jooq-generator.
 */
@Generated({"jooq-generator:"})
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetsColumns {

    /**
     * The column <code>PUBLIC.PETS.ID</code>.
     */
    public final String ID = "ID";

    /**
     * The column <code>PUBLIC.PETS.NAME</code>.
     */
    public final String NAME = "NAME";

    /**
     * The column <code>PUBLIC.PETS.BIRTH_DATE</code>.
     */
    public final String BIRTH_DATE = "BIRTH_DATE";

    /**
     * The column <code>PUBLIC.PETS.TYPE_ID</code>.
     */
    public final String TYPE_ID = "TYPE_ID";

    /**
     * The column <code>PUBLIC.PETS.OWNER_ID</code>.
     */
    public final String OWNER_ID = "OWNER_ID";

}