package org.labun.jooq.subgenerators.column;

import javax.annotation.Generated;

/**
 * This class is generated by jooq-generator.
 */
@Generated({"jooq-generator:"})
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecialtiesColumns {

    /**
     * The column <code>PUBLIC.SPECIALTIES.ID</code>.
     */
    public final String ID = "ID";

    /**
     * The column <code>PUBLIC.SPECIALTIES.NAME</code>.
     */
    public final String NAME = "NAME";

}