package org.labun.jooq.subgenerators.column;

import javax.annotation.Generated;

/**
 * This class is generated by jooq-generator.
 */
@Generated({"jooq-generator:"})
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VetSpecialtiesColumns {

    /**
     * The column <code>PUBLIC.VET_SPECIALTIES.VET_ID</code>.
     */
    public final String VET_ID = "VET_ID";

    /**
     * The column <code>PUBLIC.VET_SPECIALTIES.SPECIALTY_ID</code>.
     */
    public final String SPECIALTY_ID = "SPECIALTY_ID";

}