package org.labun.jooq.subgenerators.column;

import javax.annotation.Generated;

/**
 * This class is generated by jooq-generator.
 */
@Generated({"jooq-generator:"})
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VisitsColumns {

    /**
     * The column <code>PUBLIC.VISITS.ID</code>.
     */
    public final String ID = "ID";

    /**
     * The column <code>PUBLIC.VISITS.PET_ID</code>.
     */
    public final String PET_ID = "PET_ID";

    /**
     * The column <code>PUBLIC.VISITS.VISIT_DATE</code>.
     */
    public final String VISIT_DATE = "VISIT_DATE";

    /**
     * The column <code>PUBLIC.VISITS.DESCRIPTION</code>.
     */
    public final String DESCRIPTION = "DESCRIPTION";

}