package org.labun.jooq.subgenerators;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
* This class is generated by jooq-generator.
*/
@Generated({"jooq-generator:"})
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Catalog extends CatalogImpl {

  /**
  * The reference instance of <code>$schema.name</code>
  */
  public static final Catalog INSTANCE = new Catalog();

  /**
  * No further instances allowed
  */
  private Catalog() {
    super("");
  }

  /**
  * The schema <code>PUBLIC</code>.
  */
  public final Public PUBLIC = org.labun.jooq.subgenerators.Public.PUBLIC;

  @Override
  public final List<Schema> getSchemas() {
    List result = new ArrayList();
    result.addAll(getSchemas0());
    return result;
  }

  private final List<Schema> getSchemas0() {
    return Arrays.<Schema>asList(PUBLIC);
  }
}
