package org.labun.jooq.subgenerators;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
* This class is generated by jooq-generator.
*/
@Generated({"jooq-generator:"})
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PublicIndexes {

    public static final Index INDEX_8 = Indexes.INDEX_8 ;
    public static final Index PRIMARY_KEY_8 = Indexes.PRIMARY_KEY_8 ;
    public static final Index CONSTRAINT_INDEX_2 = Indexes.CONSTRAINT_INDEX_2 ;
    public static final Index CONSTRAINT_INDEX_25 = Indexes.CONSTRAINT_INDEX_25 ;
    public static final Index INDEX_25 = Indexes.INDEX_25 ;
    public static final Index PRIMARY_KEY_25 = Indexes.PRIMARY_KEY_25 ;
    public static final Index INDEX_4 = Indexes.INDEX_4 ;
    public static final Index PRIMARY_KEY_4 = Indexes.PRIMARY_KEY_4 ;
    public static final Index INDEX_4C = Indexes.INDEX_4C ;
    public static final Index PRIMARY_KEY_4C = Indexes.PRIMARY_KEY_4C ;
    public static final Index INDEX_2 = Indexes.INDEX_2 ;
    public static final Index PRIMARY_KEY_2 = Indexes.PRIMARY_KEY_2 ;
    public static final Index CONSTRAINT_INDEX_7 = Indexes.CONSTRAINT_INDEX_7 ;
    public static final Index CONSTRAINT_INDEX_7A = Indexes.CONSTRAINT_INDEX_7A ;
    public static final Index CONSTRAINT_INDEX_7AC = Indexes.CONSTRAINT_INDEX_7AC ;
    public static final Index CONSTRAINT_INDEX_9 = Indexes.CONSTRAINT_INDEX_9 ;
    public static final Index PRIMARY_KEY_9 = Indexes.PRIMARY_KEY_9 ;

  private static class Indexes extends AbstractKeys {
    public static Index INDEX_8 = createIndex("INDEX_8", org.labun.jooq.subgenerators.table.OwnersTable.OWNERS, new OrderField[] { org.labun.jooq.subgenerators.table.OwnersTable.OWNERS.LAST_NAME }, false);
    public static Index PRIMARY_KEY_8 = createIndex("PRIMARY_KEY_8", org.labun.jooq.subgenerators.table.OwnersTable.OWNERS, new OrderField[] { org.labun.jooq.subgenerators.table.OwnersTable.OWNERS.ID }, true);
    public static Index CONSTRAINT_INDEX_2 = createIndex("CONSTRAINT_INDEX_2", org.labun.jooq.subgenerators.table.PetsTable.PETS, new OrderField[] { org.labun.jooq.subgenerators.table.PetsTable.PETS.OWNER_ID }, false);
    public static Index CONSTRAINT_INDEX_25 = createIndex("CONSTRAINT_INDEX_25", org.labun.jooq.subgenerators.table.PetsTable.PETS, new OrderField[] { org.labun.jooq.subgenerators.table.PetsTable.PETS.TYPE_ID }, false);
    public static Index INDEX_25 = createIndex("INDEX_25", org.labun.jooq.subgenerators.table.PetsTable.PETS, new OrderField[] { org.labun.jooq.subgenerators.table.PetsTable.PETS.NAME }, false);
    public static Index PRIMARY_KEY_25 = createIndex("PRIMARY_KEY_25", org.labun.jooq.subgenerators.table.PetsTable.PETS, new OrderField[] { org.labun.jooq.subgenerators.table.PetsTable.PETS.ID }, true);
    public static Index INDEX_4 = createIndex("INDEX_4", org.labun.jooq.subgenerators.table.SpecialtiesTable.SPECIALTIES, new OrderField[] { org.labun.jooq.subgenerators.table.SpecialtiesTable.SPECIALTIES.NAME }, false);
    public static Index PRIMARY_KEY_4 = createIndex("PRIMARY_KEY_4", org.labun.jooq.subgenerators.table.SpecialtiesTable.SPECIALTIES, new OrderField[] { org.labun.jooq.subgenerators.table.SpecialtiesTable.SPECIALTIES.ID }, true);
    public static Index INDEX_4C = createIndex("INDEX_4C", org.labun.jooq.subgenerators.table.TypesTable.TYPES, new OrderField[] { org.labun.jooq.subgenerators.table.TypesTable.TYPES.NAME }, false);
    public static Index PRIMARY_KEY_4C = createIndex("PRIMARY_KEY_4C", org.labun.jooq.subgenerators.table.TypesTable.TYPES, new OrderField[] { org.labun.jooq.subgenerators.table.TypesTable.TYPES.ID }, true);
    public static Index INDEX_2 = createIndex("INDEX_2", org.labun.jooq.subgenerators.table.VetsTable.VETS, new OrderField[] { org.labun.jooq.subgenerators.table.VetsTable.VETS.LAST_NAME }, false);
    public static Index PRIMARY_KEY_2 = createIndex("PRIMARY_KEY_2", org.labun.jooq.subgenerators.table.VetsTable.VETS, new OrderField[] { org.labun.jooq.subgenerators.table.VetsTable.VETS.ID }, true);
    public static Index CONSTRAINT_INDEX_7 = createIndex("CONSTRAINT_INDEX_7", org.labun.jooq.subgenerators.table.VetSpecialtiesTable.VET_SPECIALTIES, new OrderField[] { org.labun.jooq.subgenerators.table.VetSpecialtiesTable.VET_SPECIALTIES.VET_ID }, false);
    public static Index CONSTRAINT_INDEX_7A = createIndex("CONSTRAINT_INDEX_7A", org.labun.jooq.subgenerators.table.VetSpecialtiesTable.VET_SPECIALTIES, new OrderField[] { org.labun.jooq.subgenerators.table.VetSpecialtiesTable.VET_SPECIALTIES.SPECIALTY_ID }, false);
    public static Index CONSTRAINT_INDEX_7AC = createIndex("CONSTRAINT_INDEX_7AC", org.labun.jooq.subgenerators.table.VetSpecialtiesTable.VET_SPECIALTIES, new OrderField[] { org.labun.jooq.subgenerators.table.VetSpecialtiesTable.VET_SPECIALTIES.VET_ID, org.labun.jooq.subgenerators.table.VetSpecialtiesTable.VET_SPECIALTIES.SPECIALTY_ID }, true);
    public static Index CONSTRAINT_INDEX_9 = createIndex("CONSTRAINT_INDEX_9", org.labun.jooq.subgenerators.table.VisitsTable.VISITS, new OrderField[] { org.labun.jooq.subgenerators.table.VisitsTable.VISITS.PET_ID }, false);
    public static Index PRIMARY_KEY_9 = createIndex("PRIMARY_KEY_9", org.labun.jooq.subgenerators.table.VisitsTable.VISITS, new OrderField[] { org.labun.jooq.subgenerators.table.VisitsTable.VISITS.ID }, true);
  }

}
