package org.labun.jooq.subgenerators.table;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
* This class is generated by jooq-generator.
*/
@Generated({"jooq-generator:"})
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetsTable extends TableImpl<org.labun.jooq.subgenerators.record.PetsRecord> {

/**
* The reference instance of <code>PUBLIC.PETS</code>
*/
public static final PetsTable PETS = new PetsTable();

  /**
  * The class holding records for this type
  */
  @Override
  public Class<org.labun.jooq.subgenerators.record.PetsRecord> getRecordType() {
    return org.labun.jooq.subgenerators.record.PetsRecord.class;
  }

  /**
  * Create an aliased <code>PUBLIC.PETS</code> table reference
  */
  public PetsTable() {
    this(DSL.name("PETS"), null);
  }

  /**
  * Create an aliased <code>PUBLIC.PETS</code> table reference
  */
  public PetsTable(String alias) {
    this(DSL.name(alias), PETS);
  }

  /**
  * Create an aliased <code>PUBLIC.PETS</code> table reference
  */
  public PetsTable(Name alias) {
    this(alias, PETS);
  }

  private PetsTable(Name alias, Table<org.labun.jooq.subgenerators.record.PetsRecord> aliased) {
    this(alias, aliased, null);
  }

  private PetsTable(Name alias, Table<org.labun.jooq.subgenerators.record.PetsRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, "");
  }

  /**
  * The column <code>PUBLIC.PETS.ID</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.PetsRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

  /**
  * The column <code>PUBLIC.PETS.NAME</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.PetsRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

  /**
  * The column <code>PUBLIC.PETS.BIRTH_DATE</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.PetsRecord, java.time.LocalDate> BIRTH_DATE = createField("BIRTH_DATE", org.jooq.impl.SQLDataType.LOCALDATE, this, "");

  /**
  * The column <code>PUBLIC.PETS.TYPE_ID</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.PetsRecord, java.lang.Integer> TYPE_ID = createField("TYPE_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

  /**
  * The column <code>PUBLIC.PETS.OWNER_ID</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.PetsRecord, java.lang.Integer> OWNER_ID = createField("OWNER_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");


  /**
  * {@inheritDoc}
  */
  @Override
  public Schema getSchema() {
    return org.labun.jooq.subgenerators.Public.PUBLIC;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public PetsTable as(String alias) {
    return new PetsTable(DSL.name(alias), this);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public PetsTable as(Name alias) {
    return new PetsTable(alias, this);
  }

  /**
  * Rename this table
  */
  @Override
  public PetsTable rename(String name) {
    return new PetsTable(DSL.name(name), null);
  }

  /**
  * Rename this table
  */
  @Override
  public PetsTable rename(Name name) {
    return new PetsTable(name, null);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public List<Index> getIndexes() {
    return Arrays.<Index>asList(org.labun.jooq.subgenerators.PublicIndexes.CONSTRAINT_INDEX_2, org.labun.jooq.subgenerators.PublicIndexes.CONSTRAINT_INDEX_25, org.labun.jooq.subgenerators.PublicIndexes.INDEX_25, org.labun.jooq.subgenerators.PublicIndexes.PRIMARY_KEY_25);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public Identity<org.labun.jooq.subgenerators.record.PetsRecord, java.lang.Integer> getIdentity() {
    return org.labun.jooq.subgenerators.PublicKeys.IDENTITY_PETS;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public UniqueKey<org.labun.jooq.subgenerators.record.PetsRecord> getPrimaryKey() {
    return org.labun.jooq.subgenerators.PublicKeys.CONSTRAINT_25;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public List<UniqueKey<org.labun.jooq.subgenerators.record.PetsRecord>> getKeys() {
    return Arrays.<UniqueKey<org.labun.jooq.subgenerators.record.PetsRecord>>asList(org.labun.jooq.subgenerators.PublicKeys.CONSTRAINT_25);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public List<ForeignKey<org.labun.jooq.subgenerators.record.PetsRecord, ?>> getReferences() {
    return Arrays.<ForeignKey<org.labun.jooq.subgenerators.record.PetsRecord, ?>>asList(org.labun.jooq.subgenerators.PublicKeys.CONSTRAINT_256B, org.labun.jooq.subgenerators.PublicKeys.CONSTRAINT_256);
  }
}