package org.labun.jooq.subgenerators.table;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
* This class is generated by jooq-generator.
*/
@Generated({"jooq-generator:"})
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VetSpecialtiesTable extends TableImpl<org.labun.jooq.subgenerators.record.VetSpecialtiesRecord> {

/**
* The reference instance of <code>PUBLIC.VET_SPECIALTIES</code>
*/
public static final VetSpecialtiesTable VET_SPECIALTIES = new VetSpecialtiesTable();

  /**
  * The class holding records for this type
  */
  @Override
  public Class<org.labun.jooq.subgenerators.record.VetSpecialtiesRecord> getRecordType() {
    return org.labun.jooq.subgenerators.record.VetSpecialtiesRecord.class;
  }

  /**
  * Create an aliased <code>PUBLIC.VET_SPECIALTIES</code> table reference
  */
  public VetSpecialtiesTable() {
    this(DSL.name("VET_SPECIALTIES"), null);
  }

  /**
  * Create an aliased <code>PUBLIC.VET_SPECIALTIES</code> table reference
  */
  public VetSpecialtiesTable(String alias) {
    this(DSL.name(alias), VET_SPECIALTIES);
  }

  /**
  * Create an aliased <code>PUBLIC.VET_SPECIALTIES</code> table reference
  */
  public VetSpecialtiesTable(Name alias) {
    this(alias, VET_SPECIALTIES);
  }

  private VetSpecialtiesTable(Name alias, Table<org.labun.jooq.subgenerators.record.VetSpecialtiesRecord> aliased) {
    this(alias, aliased, null);
  }

  private VetSpecialtiesTable(Name alias, Table<org.labun.jooq.subgenerators.record.VetSpecialtiesRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, "");
  }

  /**
  * The column <code>PUBLIC.VET_SPECIALTIES.VET_ID</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VetSpecialtiesRecord, java.lang.Integer> VET_ID = createField("VET_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

  /**
  * The column <code>PUBLIC.VET_SPECIALTIES.SPECIALTY_ID</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VetSpecialtiesRecord, java.lang.Integer> SPECIALTY_ID = createField("SPECIALTY_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");


  /**
  * {@inheritDoc}
  */
  @Override
  public Schema getSchema() {
    return org.labun.jooq.subgenerators.Public.PUBLIC;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public VetSpecialtiesTable as(String alias) {
    return new VetSpecialtiesTable(DSL.name(alias), this);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public VetSpecialtiesTable as(Name alias) {
    return new VetSpecialtiesTable(alias, this);
  }

  /**
  * Rename this table
  */
  @Override
  public VetSpecialtiesTable rename(String name) {
    return new VetSpecialtiesTable(DSL.name(name), null);
  }

  /**
  * Rename this table
  */
  @Override
  public VetSpecialtiesTable rename(Name name) {
    return new VetSpecialtiesTable(name, null);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public List<Index> getIndexes() {
    return Arrays.<Index>asList(org.labun.jooq.subgenerators.PublicIndexes.CONSTRAINT_INDEX_7, org.labun.jooq.subgenerators.PublicIndexes.CONSTRAINT_INDEX_7A, org.labun.jooq.subgenerators.PublicIndexes.CONSTRAINT_INDEX_7AC);
  }



  /**
  * {@inheritDoc}
  */
  @Override
  public List<UniqueKey<org.labun.jooq.subgenerators.record.VetSpecialtiesRecord>> getKeys() {
    return Arrays.<UniqueKey<org.labun.jooq.subgenerators.record.VetSpecialtiesRecord>>asList(org.labun.jooq.subgenerators.PublicKeys.CONSTRAINT_7AC);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public List<ForeignKey<org.labun.jooq.subgenerators.record.VetSpecialtiesRecord, ?>> getReferences() {
    return Arrays.<ForeignKey<org.labun.jooq.subgenerators.record.VetSpecialtiesRecord, ?>>asList(org.labun.jooq.subgenerators.PublicKeys.CONSTRAINT_7, org.labun.jooq.subgenerators.PublicKeys.CONSTRAINT_7A);
  }
}