package org.labun.jooq.subgenerators.table;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
* This class is generated by jooq-generator.
*/
@Generated({"jooq-generator:"})
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VetsTable extends TableImpl<org.labun.jooq.subgenerators.record.VetsRecord> {

/**
* The reference instance of <code>PUBLIC.VETS</code>
*/
public static final VetsTable VETS = new VetsTable();

  /**
  * The class holding records for this type
  */
  @Override
  public Class<org.labun.jooq.subgenerators.record.VetsRecord> getRecordType() {
    return org.labun.jooq.subgenerators.record.VetsRecord.class;
  }

  /**
  * Create an aliased <code>PUBLIC.VETS</code> table reference
  */
  public VetsTable() {
    this(DSL.name("VETS"), null);
  }

  /**
  * Create an aliased <code>PUBLIC.VETS</code> table reference
  */
  public VetsTable(String alias) {
    this(DSL.name(alias), VETS);
  }

  /**
  * Create an aliased <code>PUBLIC.VETS</code> table reference
  */
  public VetsTable(Name alias) {
    this(alias, VETS);
  }

  private VetsTable(Name alias, Table<org.labun.jooq.subgenerators.record.VetsRecord> aliased) {
    this(alias, aliased, null);
  }

  private VetsTable(Name alias, Table<org.labun.jooq.subgenerators.record.VetsRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, "");
  }

  /**
  * The column <code>PUBLIC.VETS.ID</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VetsRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

  /**
  * The column <code>PUBLIC.VETS.FIRST_NAME</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VetsRecord, java.lang.String> FIRST_NAME = createField("FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

  /**
  * The column <code>PUBLIC.VETS.LAST_NAME</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VetsRecord, java.lang.String> LAST_NAME = createField("LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

  /**
  * The column <code>PUBLIC.VETS.AGE</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VetsRecord, java.lang.Integer> AGE = createField("AGE", org.jooq.impl.SQLDataType.INTEGER, this, "");

  /**
  * The column <code>PUBLIC.VETS.BIRTH_DATE</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VetsRecord, java.time.LocalDate> BIRTH_DATE = createField("BIRTH_DATE", org.jooq.impl.SQLDataType.LOCALDATE, this, "");

  /**
  * The column <code>PUBLIC.VETS.CREATED</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VetsRecord, java.time.LocalDateTime> CREATED = createField("CREATED", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

  /**
  * The column <code>PUBLIC.VETS.LAST_MODIFIED</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VetsRecord, java.time.LocalDateTime> LAST_MODIFIED = createField("LAST_MODIFIED", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

  /**
  * The column <code>PUBLIC.VETS.PROFILE_PICTURE</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VetsRecord, byte[]> PROFILE_PICTURE = createField("PROFILE_PICTURE", org.jooq.impl.SQLDataType.BLOB, this, "");


  /**
  * {@inheritDoc}
  */
  @Override
  public Schema getSchema() {
    return org.labun.jooq.subgenerators.Public.PUBLIC;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public VetsTable as(String alias) {
    return new VetsTable(DSL.name(alias), this);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public VetsTable as(Name alias) {
    return new VetsTable(alias, this);
  }

  /**
  * Rename this table
  */
  @Override
  public VetsTable rename(String name) {
    return new VetsTable(DSL.name(name), null);
  }

  /**
  * Rename this table
  */
  @Override
  public VetsTable rename(Name name) {
    return new VetsTable(name, null);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public List<Index> getIndexes() {
    return Arrays.<Index>asList(org.labun.jooq.subgenerators.PublicIndexes.INDEX_2, org.labun.jooq.subgenerators.PublicIndexes.PRIMARY_KEY_2);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public Identity<org.labun.jooq.subgenerators.record.VetsRecord, java.lang.Integer> getIdentity() {
    return org.labun.jooq.subgenerators.PublicKeys.IDENTITY_VETS;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public UniqueKey<org.labun.jooq.subgenerators.record.VetsRecord> getPrimaryKey() {
    return org.labun.jooq.subgenerators.PublicKeys.CONSTRAINT_2;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public List<UniqueKey<org.labun.jooq.subgenerators.record.VetsRecord>> getKeys() {
    return Arrays.<UniqueKey<org.labun.jooq.subgenerators.record.VetsRecord>>asList(org.labun.jooq.subgenerators.PublicKeys.CONSTRAINT_2);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public List<ForeignKey<org.labun.jooq.subgenerators.record.VetsRecord, ?>> getReferences() {
    return Arrays.<ForeignKey<org.labun.jooq.subgenerators.record.VetsRecord, ?>>asList();
  }
}