package org.labun.jooq.subgenerators.table;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
* This class is generated by jooq-generator.
*/
@Generated({"jooq-generator:"})
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VisitsTable extends TableImpl<org.labun.jooq.subgenerators.record.VisitsRecord> {

/**
* The reference instance of <code>PUBLIC.VISITS</code>
*/
public static final VisitsTable VISITS = new VisitsTable();

  /**
  * The class holding records for this type
  */
  @Override
  public Class<org.labun.jooq.subgenerators.record.VisitsRecord> getRecordType() {
    return org.labun.jooq.subgenerators.record.VisitsRecord.class;
  }

  /**
  * Create an aliased <code>PUBLIC.VISITS</code> table reference
  */
  public VisitsTable() {
    this(DSL.name("VISITS"), null);
  }

  /**
  * Create an aliased <code>PUBLIC.VISITS</code> table reference
  */
  public VisitsTable(String alias) {
    this(DSL.name(alias), VISITS);
  }

  /**
  * Create an aliased <code>PUBLIC.VISITS</code> table reference
  */
  public VisitsTable(Name alias) {
    this(alias, VISITS);
  }

  private VisitsTable(Name alias, Table<org.labun.jooq.subgenerators.record.VisitsRecord> aliased) {
    this(alias, aliased, null);
  }

  private VisitsTable(Name alias, Table<org.labun.jooq.subgenerators.record.VisitsRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, "");
  }

  /**
  * The column <code>PUBLIC.VISITS.ID</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VisitsRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

  /**
  * The column <code>PUBLIC.VISITS.PET_ID</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VisitsRecord, java.lang.Integer> PET_ID = createField("PET_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

  /**
  * The column <code>PUBLIC.VISITS.VISIT_DATE</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VisitsRecord, java.time.LocalDate> VISIT_DATE = createField("VISIT_DATE", org.jooq.impl.SQLDataType.LOCALDATE, this, "");

  /**
  * The column <code>PUBLIC.VISITS.DESCRIPTION</code>.
  */
  public final TableField<org.labun.jooq.subgenerators.record.VisitsRecord, java.lang.String> DESCRIPTION = createField("DESCRIPTION", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");


  /**
  * {@inheritDoc}
  */
  @Override
  public Schema getSchema() {
    return org.labun.jooq.subgenerators.Public.PUBLIC;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public VisitsTable as(String alias) {
    return new VisitsTable(DSL.name(alias), this);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public VisitsTable as(Name alias) {
    return new VisitsTable(alias, this);
  }

  /**
  * Rename this table
  */
  @Override
  public VisitsTable rename(String name) {
    return new VisitsTable(DSL.name(name), null);
  }

  /**
  * Rename this table
  */
  @Override
  public VisitsTable rename(Name name) {
    return new VisitsTable(name, null);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public List<Index> getIndexes() {
    return Arrays.<Index>asList(org.labun.jooq.subgenerators.PublicIndexes.CONSTRAINT_INDEX_9, org.labun.jooq.subgenerators.PublicIndexes.PRIMARY_KEY_9);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public Identity<org.labun.jooq.subgenerators.record.VisitsRecord, java.lang.Integer> getIdentity() {
    return org.labun.jooq.subgenerators.PublicKeys.IDENTITY_VISITS;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public UniqueKey<org.labun.jooq.subgenerators.record.VisitsRecord> getPrimaryKey() {
    return org.labun.jooq.subgenerators.PublicKeys.CONSTRAINT_9;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public List<UniqueKey<org.labun.jooq.subgenerators.record.VisitsRecord>> getKeys() {
    return Arrays.<UniqueKey<org.labun.jooq.subgenerators.record.VisitsRecord>>asList(org.labun.jooq.subgenerators.PublicKeys.CONSTRAINT_9);
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public List<ForeignKey<org.labun.jooq.subgenerators.record.VisitsRecord, ?>> getReferences() {
    return Arrays.<ForeignKey<org.labun.jooq.subgenerators.record.VisitsRecord, ?>>asList(org.labun.jooq.subgenerators.PublicKeys.CONSTRAINT_96);
  }
}