package org.labun.jooq.subgenerators.record;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

/**
* This class is generated by jooq-generator.
*/
@Generated({"jooq-generator:"})
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class OwnersRecord extends UpdatableRecordImpl<OwnersRecord> implements Record6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {


  /**
  * Setter for <code>PUBLIC.OWNERS.ID</code>
  */
  public OwnersRecord id(java.lang.Integer value) {
    set(0, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.OWNERS.ID</code>.
  */
  public java.lang.Integer id() {
    return (java.lang.Integer) get(0);
  }

  /**
  * Setter for <code>PUBLIC.OWNERS.FIRST_NAME</code>
  */
  public OwnersRecord firstName(java.lang.String value) {
    set(1, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.OWNERS.FIRST_NAME</code>.
  */
  public java.lang.String firstName() {
    return (java.lang.String) get(1);
  }

  /**
  * Setter for <code>PUBLIC.OWNERS.LAST_NAME</code>
  */
  public OwnersRecord lastName(java.lang.String value) {
    set(2, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.OWNERS.LAST_NAME</code>.
  */
  public java.lang.String lastName() {
    return (java.lang.String) get(2);
  }

  /**
  * Setter for <code>PUBLIC.OWNERS.ADDRESS</code>
  */
  public OwnersRecord address(java.lang.String value) {
    set(3, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.OWNERS.ADDRESS</code>.
  */
  public java.lang.String address() {
    return (java.lang.String) get(3);
  }

  /**
  * Setter for <code>PUBLIC.OWNERS.CITY</code>
  */
  public OwnersRecord city(java.lang.String value) {
    set(4, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.OWNERS.CITY</code>.
  */
  public java.lang.String city() {
    return (java.lang.String) get(4);
  }

  /**
  * Setter for <code>PUBLIC.OWNERS.TELEPHONE</code>
  */
  public OwnersRecord telephone(java.lang.String value) {
    set(5, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.OWNERS.TELEPHONE</code>.
  */
  public java.lang.String telephone() {
    return (java.lang.String) get(5);
  }


  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
  * {@inheritDoc}
  */
  @Override
  public Record1<java.lang.Integer> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record6 type implementation
  // -------------------------------------------------------------------------

  /**
  * {@inheritDoc}
  */
  @Override
  public Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
    return (Row6) super.fieldsRow();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
    return (Row6) super.valuesRow();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.Integer> field1() {
    return org.labun.jooq.subgenerators.table.OwnersTable.OWNERS.ID;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.String> field2() {
    return org.labun.jooq.subgenerators.table.OwnersTable.OWNERS.FIRST_NAME;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.String> field3() {
    return org.labun.jooq.subgenerators.table.OwnersTable.OWNERS.LAST_NAME;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.String> field4() {
    return org.labun.jooq.subgenerators.table.OwnersTable.OWNERS.ADDRESS;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.String> field5() {
    return org.labun.jooq.subgenerators.table.OwnersTable.OWNERS.CITY;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.String> field6() {
    return org.labun.jooq.subgenerators.table.OwnersTable.OWNERS.TELEPHONE;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.Integer component1() {
    return id();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String component2() {
    return firstName();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String component3() {
    return lastName();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String component4() {
    return address();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String component5() {
    return city();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String component6() {
    return telephone();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.Integer value1() {
    return id();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String value2() {
    return firstName();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String value3() {
    return lastName();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String value4() {
    return address();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String value5() {
    return city();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String value6() {
    return telephone();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public OwnersRecord value1(java.lang.Integer value) {
    id(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public OwnersRecord value2(java.lang.String value) {
    firstName(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public OwnersRecord value3(java.lang.String value) {
    lastName(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public OwnersRecord value4(java.lang.String value) {
    address(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public OwnersRecord value5(java.lang.String value) {
    city(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public OwnersRecord value6(java.lang.String value) {
    telephone(value);
    return this;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public OwnersRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    return this;
  }


  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
  * Create a detached OwnersRecord
  */
  public OwnersRecord() {
    super(org.labun.jooq.subgenerators.table.OwnersTable.OWNERS);
  }

  /**
  * Create a detached, initialised OwnersRecord
  */
  public OwnersRecord(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6) {
    super(org.labun.jooq.subgenerators.table.OwnersTable.OWNERS);

    set(0, value1);
    set(1, value2);
    set(2, value3);
    set(3, value4);
    set(4, value5);
    set(5, value6);
  }
}
