package org.labun.jooq.subgenerators.record;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

/**
* This class is generated by jooq-generator.
*/
@Generated({"jooq-generator:"})
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VetsRecord extends UpdatableRecordImpl<VetsRecord> implements Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.time.LocalDate, java.time.LocalDateTime, java.time.LocalDateTime, byte[]> {


  /**
  * Setter for <code>PUBLIC.VETS.ID</code>
  */
  public VetsRecord id(java.lang.Integer value) {
    set(0, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.VETS.ID</code>.
  */
  public java.lang.Integer id() {
    return (java.lang.Integer) get(0);
  }

  /**
  * Setter for <code>PUBLIC.VETS.FIRST_NAME</code>
  */
  public VetsRecord firstName(java.lang.String value) {
    set(1, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.VETS.FIRST_NAME</code>.
  */
  public java.lang.String firstName() {
    return (java.lang.String) get(1);
  }

  /**
  * Setter for <code>PUBLIC.VETS.LAST_NAME</code>
  */
  public VetsRecord lastName(java.lang.String value) {
    set(2, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.VETS.LAST_NAME</code>.
  */
  public java.lang.String lastName() {
    return (java.lang.String) get(2);
  }

  /**
  * Setter for <code>PUBLIC.VETS.AGE</code>
  */
  public VetsRecord age(java.lang.Integer value) {
    set(3, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.VETS.AGE</code>.
  */
  public java.lang.Integer age() {
    return (java.lang.Integer) get(3);
  }

  /**
  * Setter for <code>PUBLIC.VETS.BIRTH_DATE</code>
  */
  public VetsRecord birthDate(java.time.LocalDate value) {
    set(4, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.VETS.BIRTH_DATE</code>.
  */
  public java.time.LocalDate birthDate() {
    return (java.time.LocalDate) get(4);
  }

  /**
  * Setter for <code>PUBLIC.VETS.CREATED</code>
  */
  public VetsRecord created(java.time.LocalDateTime value) {
    set(5, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.VETS.CREATED</code>.
  */
  public java.time.LocalDateTime created() {
    return (java.time.LocalDateTime) get(5);
  }

  /**
  * Setter for <code>PUBLIC.VETS.LAST_MODIFIED</code>
  */
  public VetsRecord lastModified(java.time.LocalDateTime value) {
    set(6, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.VETS.LAST_MODIFIED</code>.
  */
  public java.time.LocalDateTime lastModified() {
    return (java.time.LocalDateTime) get(6);
  }

  /**
  * Setter for <code>PUBLIC.VETS.PROFILE_PICTURE</code>
  */
  public VetsRecord profilePicture(byte[] value) {
    set(7, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.VETS.PROFILE_PICTURE</code>.
  */
  public byte[] profilePicture() {
    return (byte[]) get(7);
  }


  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
  * {@inheritDoc}
  */
  @Override
  public Record1<java.lang.Integer> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record8 type implementation
  // -------------------------------------------------------------------------

  /**
  * {@inheritDoc}
  */
  @Override
  public Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.time.LocalDate, java.time.LocalDateTime, java.time.LocalDateTime, byte[]> fieldsRow() {
    return (Row8) super.fieldsRow();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.time.LocalDate, java.time.LocalDateTime, java.time.LocalDateTime, byte[]> valuesRow() {
    return (Row8) super.valuesRow();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.Integer> field1() {
    return org.labun.jooq.subgenerators.table.VetsTable.VETS.ID;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.String> field2() {
    return org.labun.jooq.subgenerators.table.VetsTable.VETS.FIRST_NAME;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.String> field3() {
    return org.labun.jooq.subgenerators.table.VetsTable.VETS.LAST_NAME;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.Integer> field4() {
    return org.labun.jooq.subgenerators.table.VetsTable.VETS.AGE;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.time.LocalDate> field5() {
    return org.labun.jooq.subgenerators.table.VetsTable.VETS.BIRTH_DATE;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.time.LocalDateTime> field6() {
    return org.labun.jooq.subgenerators.table.VetsTable.VETS.CREATED;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.time.LocalDateTime> field7() {
    return org.labun.jooq.subgenerators.table.VetsTable.VETS.LAST_MODIFIED;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<byte[]> field8() {
    return org.labun.jooq.subgenerators.table.VetsTable.VETS.PROFILE_PICTURE;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.Integer component1() {
    return id();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String component2() {
    return firstName();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String component3() {
    return lastName();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.Integer component4() {
    return age();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.time.LocalDate component5() {
    return birthDate();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.time.LocalDateTime component6() {
    return created();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.time.LocalDateTime component7() {
    return lastModified();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public byte[] component8() {
    return profilePicture();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.Integer value1() {
    return id();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String value2() {
    return firstName();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String value3() {
    return lastName();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.Integer value4() {
    return age();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.time.LocalDate value5() {
    return birthDate();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.time.LocalDateTime value6() {
    return created();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.time.LocalDateTime value7() {
    return lastModified();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public byte[] value8() {
    return profilePicture();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public VetsRecord value1(java.lang.Integer value) {
    id(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public VetsRecord value2(java.lang.String value) {
    firstName(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public VetsRecord value3(java.lang.String value) {
    lastName(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public VetsRecord value4(java.lang.Integer value) {
    age(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public VetsRecord value5(java.time.LocalDate value) {
    birthDate(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public VetsRecord value6(java.time.LocalDateTime value) {
    created(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public VetsRecord value7(java.time.LocalDateTime value) {
    lastModified(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public VetsRecord value8(byte[] value) {
    profilePicture(value);
    return this;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public VetsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4, java.time.LocalDate value5, java.time.LocalDateTime value6, java.time.LocalDateTime value7, byte[] value8) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    return this;
  }


  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
  * Create a detached VetsRecord
  */
  public VetsRecord() {
    super(org.labun.jooq.subgenerators.table.VetsTable.VETS);
  }

  /**
  * Create a detached, initialised VetsRecord
  */
  public VetsRecord(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4, java.time.LocalDate value5, java.time.LocalDateTime value6, java.time.LocalDateTime value7, byte[] value8) {
    super(org.labun.jooq.subgenerators.table.VetsTable.VETS);

    set(0, value1);
    set(1, value2);
    set(2, value3);
    set(3, value4);
    set(4, value5);
    set(5, value6);
    set(6, value7);
    set(7, value8);
  }
}
