package org.labun.jooq.subgenerators.record;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

/**
* This class is generated by jooq-generator.
*/
@Generated({"jooq-generator:"})
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VisitsRecord extends UpdatableRecordImpl<VisitsRecord> implements Record4<java.lang.Integer, java.lang.Integer, java.time.LocalDate, java.lang.String> {


  /**
  * Setter for <code>PUBLIC.VISITS.ID</code>
  */
  public VisitsRecord id(java.lang.Integer value) {
    set(0, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.VISITS.ID</code>.
  */
  public java.lang.Integer id() {
    return (java.lang.Integer) get(0);
  }

  /**
  * Setter for <code>PUBLIC.VISITS.PET_ID</code>
  */
  public VisitsRecord petId(java.lang.Integer value) {
    set(1, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.VISITS.PET_ID</code>.
  */
  public java.lang.Integer petId() {
    return (java.lang.Integer) get(1);
  }

  /**
  * Setter for <code>PUBLIC.VISITS.VISIT_DATE</code>
  */
  public VisitsRecord visitDate(java.time.LocalDate value) {
    set(2, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.VISITS.VISIT_DATE</code>.
  */
  public java.time.LocalDate visitDate() {
    return (java.time.LocalDate) get(2);
  }

  /**
  * Setter for <code>PUBLIC.VISITS.DESCRIPTION</code>
  */
  public VisitsRecord description(java.lang.String value) {
    set(3, value);
    return this;
  }

  /**
  * Getter for <code>PUBLIC.VISITS.DESCRIPTION</code>.
  */
  public java.lang.String description() {
    return (java.lang.String) get(3);
  }


  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
  * {@inheritDoc}
  */
  @Override
  public Record1<java.lang.Integer> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record4 type implementation
  // -------------------------------------------------------------------------

  /**
  * {@inheritDoc}
  */
  @Override
  public Row4<java.lang.Integer, java.lang.Integer, java.time.LocalDate, java.lang.String> fieldsRow() {
    return (Row4) super.fieldsRow();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public Row4<java.lang.Integer, java.lang.Integer, java.time.LocalDate, java.lang.String> valuesRow() {
    return (Row4) super.valuesRow();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.Integer> field1() {
    return org.labun.jooq.subgenerators.table.VisitsTable.VISITS.ID;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.Integer> field2() {
    return org.labun.jooq.subgenerators.table.VisitsTable.VISITS.PET_ID;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.time.LocalDate> field3() {
    return org.labun.jooq.subgenerators.table.VisitsTable.VISITS.VISIT_DATE;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public Field<java.lang.String> field4() {
    return org.labun.jooq.subgenerators.table.VisitsTable.VISITS.DESCRIPTION;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.Integer component1() {
    return id();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.Integer component2() {
    return petId();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.time.LocalDate component3() {
    return visitDate();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String component4() {
    return description();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.Integer value1() {
    return id();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.Integer value2() {
    return petId();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.time.LocalDate value3() {
    return visitDate();
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public java.lang.String value4() {
    return description();
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public VisitsRecord value1(java.lang.Integer value) {
    id(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public VisitsRecord value2(java.lang.Integer value) {
    petId(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public VisitsRecord value3(java.time.LocalDate value) {
    visitDate(value);
    return this;
  }
  /**
  * {@inheritDoc}
  */
  @Override
  public VisitsRecord value4(java.lang.String value) {
    description(value);
    return this;
  }

  /**
  * {@inheritDoc}
  */
  @Override
  public VisitsRecord values(java.lang.Integer value1, java.lang.Integer value2, java.time.LocalDate value3, java.lang.String value4) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    return this;
  }


  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
  * Create a detached VisitsRecord
  */
  public VisitsRecord() {
    super(org.labun.jooq.subgenerators.table.VisitsTable.VISITS);
  }

  /**
  * Create a detached, initialised VisitsRecord
  */
  public VisitsRecord(java.lang.Integer value1, java.lang.Integer value2, java.time.LocalDate value3, java.lang.String value4) {
    super(org.labun.jooq.subgenerators.table.VisitsTable.VISITS);

    set(0, value1);
    set(1, value2);
    set(2, value3);
    set(3, value4);
  }
}
