package org.labun.jooq.codegen.table;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import javax.annotation.Generated;

/**
 * This class is generated by jooq-generator.
 */
@Generated({"jooq-generator:"})
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonTable extends TableImpl<org.labun.jooq.codegen.record.PersonRecord> {

    /**
     * The reference instance of <code>PUBLIC.PERSON</code>
     */
    public static final PersonTable PERSON = new PersonTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<org.labun.jooq.codegen.record.PersonRecord> getRecordType() {
        return org.labun.jooq.codegen.record.PersonRecord.class;
    }

    /**
     * Create a <code>PUBLIC.PERSON</code> table reference
     */
    public PersonTable() {
        this("PERSON", null);
    }

    /**
     * Create an aliased <code>PUBLIC.PERSON</code> table reference
     */
    public PersonTable(String alias) {
        this(alias, PERSON);
    }

    private PersonTable(String alias, Table<org.labun.jooq.codegen.record.PersonRecord> aliased) {
        this(alias, aliased, null);
    }

    private PersonTable (String alias, Table<org.labun.jooq.codegen.record.PersonRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * The column <code>PUBLIC.PERSON.ID</code>.
     */
    public final TableField<org.labun.jooq.codegen.record.PersonRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.PERSON.FIRST_NAME</code>.
     */
    public final TableField<org.labun.jooq.codegen.record.PersonRecord, java.lang.String> FIRST_NAME = createField("FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * The column <code>PUBLIC.PERSON.LAST_NAME</code>.
     */
    public final TableField<org.labun.jooq.codegen.record.PersonRecord, java.lang.String> LAST_NAME = createField("LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

    /**
     * The column <code>PUBLIC.PERSON.AGE</code>.
     */
    public final TableField<org.labun.jooq.codegen.record.PersonRecord, java.lang.Integer> AGE = createField("AGE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.PERSON.BIRTH_DATE</code>.
     */
    public final TableField<org.labun.jooq.codegen.record.PersonRecord, java.time.LocalDate> BIRTH_DATE = createField("BIRTH_DATE", org.jooq.impl.SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>PUBLIC.PERSON.CREATED</code>.
     */
    public final TableField<org.labun.jooq.codegen.record.PersonRecord, java.time.LocalDateTime> CREATED = createField("CREATED", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>PUBLIC.PERSON.LAST_MODIFIED</code>.
     */
    public final TableField<org.labun.jooq.codegen.record.PersonRecord, java.time.LocalDateTime> LAST_MODIFIED = createField("LAST_MODIFIED", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>PUBLIC.PERSON.PROFILE_PICTURE</code>.
     */
    public final TableField<org.labun.jooq.codegen.record.PersonRecord, byte[]> PROFILE_PICTURE = createField("PROFILE_PICTURE", org.jooq.impl.SQLDataType.BLOB, this, "");

}