package org.labun.jooq.generator.column;

import javax.annotation.Generated;

/**
 * This class is generated by jooq-generator.
 */
@Generated({"jooq-generator:"})
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonColumns {

    /**
     * The column <code>PUBLIC.PERSON.ID</code>.
     */
    public final String ID = "ID";

    /**
     * The column <code>PUBLIC.PERSON.FIRST_NAME</code>.
     */
    public final String FIRST_NAME = "FIRST_NAME";

    /**
     * The column <code>PUBLIC.PERSON.LAST_NAME</code>.
     */
    public final String LAST_NAME = "LAST_NAME";

    /**
     * The column <code>PUBLIC.PERSON.AGE</code>.
     */
    public final String AGE = "AGE";

    /**
     * The column <code>PUBLIC.PERSON.BIRTH_DATE</code>.
     */
    public final String BIRTH_DATE = "BIRTH_DATE";

    /**
     * The column <code>PUBLIC.PERSON.CREATED</code>.
     */
    public final String CREATED = "CREATED";

    /**
     * The column <code>PUBLIC.PERSON.LAST_MODIFIED</code>.
     */
    public final String LAST_MODIFIED = "LAST_MODIFIED";

    /**
     * The column <code>PUBLIC.PERSON.PROFILE_PICTURE</code>.
     */
    public final String PROFILE_PICTURE = "PROFILE_PICTURE";

}