package org.labun.jooq.codegen.record;

import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
* This class is generated by jooq-generator.
*/
@Generated({"jooq-generator:"})
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PersonRecord extends UpdatableRecordImpl<PersonRecord> {


    /**
     * Setter for <code>PUBLIC.PERSON.ID</code>
     */
    public PersonRecord id(java.lang.Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PERSON.ID</code>.
     */
    public java.lang.Long id() {
        return (java.lang.Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.PERSON.FIRST_NAME</code>
     */
    public PersonRecord firstName(java.lang.String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PERSON.FIRST_NAME</code>.
     */
    public java.lang.String firstName() {
        return (java.lang.String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.PERSON.LAST_NAME</code>
     */
    public PersonRecord lastName(java.lang.String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PERSON.LAST_NAME</code>.
     */
    public java.lang.String lastName() {
        return (java.lang.String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.PERSON.AGE</code>
     */
    public PersonRecord age(java.lang.Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PERSON.AGE</code>.
     */
    public java.lang.Integer age() {
        return (java.lang.Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.PERSON.BIRTH_DATE</code>
     */
    public PersonRecord birthDate(java.time.LocalDate value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PERSON.BIRTH_DATE</code>.
     */
    public java.time.LocalDate birthDate() {
        return (java.time.LocalDate) get(4);
    }

    /**
     * Setter for <code>PUBLIC.PERSON.CREATED</code>
     */
    public PersonRecord created(java.time.LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PERSON.CREATED</code>.
     */
    public java.time.LocalDateTime created() {
        return (java.time.LocalDateTime) get(5);
    }

    /**
     * Setter for <code>PUBLIC.PERSON.LAST_MODIFIED</code>
     */
    public PersonRecord lastModified(java.time.LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PERSON.LAST_MODIFIED</code>.
     */
    public java.time.LocalDateTime lastModified() {
        return (java.time.LocalDateTime) get(6);
    }

    /**
     * Setter for <code>PUBLIC.PERSON.PROFILE_PICTURE</code>
     */
    public PersonRecord profilePicture(byte[] value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.PERSON.PROFILE_PICTURE</code>.
     */
    public byte[] profilePicture() {
        return (byte[]) get(7);
    }


    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GiroCommentRecord
     */
    public PersonRecord() {
        super(org.labun.jooq.codegen.table.PersonTable.PERSON);
    }
}
